version: 2

jobs:
   ubuntu20:
     # Ubuntu 20
     docker:
       - image: ubuntu:20.04
     steps:
       - checkout
       - run:
          name: Dependencies
          # yosis is in universe, if its not enabled do
          # apt-get -q update -y
          # apt-get -q install -y software-properties-common
          # add-apt-repository universe
          # tzdata is interactive so force no interaction
          command: |
              apt-get -q update -y
              DEBIAN_FRONTEND=noninteractive apt-get -q install -y libedit-dev zlib1g-dev m4 build-essential git yosys 
       - run: 
          name: Install act base
          command: |
              git clone https://github.com/asyncvlsi/act
              mkdir install
              export ACT_HOME=`pwd`/install
              cd act
              echo "===== build act base ====="
              export VLSI_TOOLS_SRC=`pwd`
              ./configure $ACT_HOME
              ./build
              echo "===== install act base ====="
              make install
              cd ..
       - run: 
          name: Install interACT base
          command: |
              git clone https://github.com/asyncvlsi/interact
              export ACT_HOME=`pwd`/install
              export PATH=$ACT_HOME/bin:$PATH
              export VLSI_TOOLS_SRC=`pwd`/act
              cd interact
              echo "===== build interACT base ====="
              ./configure
              make depend
              make
              echo "===== install interACT base ====="
              make install
              cd ..
       - run: 
          name: Build install and test
          command: |
              export ACT_HOME=`pwd`/install
              export PATH=$ACT_HOME/bin:$PATH
              export VLSI_TOOLS_SRC=`pwd`/act
              echo "===== build act addon ====="
              ./configure
              make depend
              make
              echo "===== install act addon ====="
              make install
              echo "===== test act addon ====="
              make runtest

   centos8:
    # centos 8 / rhel 8
     docker:
       - image: centos:8
     steps:
       - checkout
       - run:           
          name: Dependencies
          command: |
              yum install -y 'dnf-command(config-manager)'
              yum config-manager --set-enabled powertools -y
              yum install -y gcc gcc-c++ diffutils make libedit-devel zlib-devel m4 git
       - run: 
          name: Install act base
          command: |
              git clone https://github.com/asyncvlsi/act
              mkdir install
              export ACT_HOME=`pwd`/install
              cd act
              echo "===== build act base ====="
              export VLSI_TOOLS_SRC=`pwd`
              ./configure $ACT_HOME
              ./build
              echo "===== install act base ====="
              make install
              cd ..
       - run: 
          name: Build install and test
          command: |
              export ACT_HOME=`pwd`/install
              export PATH=$ACT_HOME/bin:$PATH
              export VLSI_TOOLS_SRC=`pwd`/act
              echo "===== build act addon ====="
              make depend
              make
              echo "===== install act addon ====="
              make install
              echo "===== test act addon  ====="
              make runtest
workflows:
   version: 2
   build:
     jobs: 
        - ubuntu20
        #- centos8 #yosys not avalible set up compile

